# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Convert a parent vector format to the list of children
#'
#' @param parents A integer vector. Parent vector format tree.
#' @param n A single integer. The number of mutations.
#' @export
#' @return
#' the list of children of tree.
getChildListFromParentVector <- function(parents, n) {
    .Call('_converTree_getChildListFromParentVector', PACKAGE = 'converTree', parents, n)
}

#' Converts a tree given as lists of children to the Newick tree format
#'
#' @param list A list. the list of children of tree.
#' @param root A single integer. The number of mutations.
#' @return
#' the string of newick format tree.
getNewickCode <- function(list, root) {
    .Call('_converTree_getNewickCode', PACKAGE = 'converTree', list, root)
}

init_boolMatrix <- function(n, m, value) {
    .Call('_converTree_init_boolMatrix', PACKAGE = 'converTree', n, m, value)
}

#' Converts a tree given as parent vector format to an ancestor matrix
#'
#' @param parents A integer vector. Parent vector format tree.
#' @param n A single integer. The number of mutations.
#' @return
#' a logical matrix;TRUE and FALSE
parentVector2ancMatrix <- function(parents, n) {
    .Call('_converTree_parentVector2ancMatrix', PACKAGE = 'converTree', parents, n)
}

#' Converts a an ancestor matrix to tree in parent vector format
#'
#' @param anc A matrix. An ancestor matrix.
#' @param n A single integer. The number of mutations.
#' @return
#' a integer vector; parent vector format tree.
ancMatrixToParVector <- function(anc, n) {
    .Call('_converTree_ancMatrixToParVector', PACKAGE = 'converTree', anc, n)
}

